export const pageTitles = {
  dash: 'DASHBOARD',
  agenda: 'AGENDA',
  clientes: 'CLIENTES',
  fin: 'FINANCEIRO',
  estoque: 'ESTOQUE',
  servicos: 'SERVIÇOS',
  barbeiros: 'BARBEIROS',
  planos: 'Planos',
  whats: 'WHATSAPP BOT',
  mkt: 'MARKETING',
  fidel: 'FIDELIDADE',
  aval: 'AVALIAÇÕES',
  config: 'CONFIGURAÇÕES',
  cres: 'PAINEL DE CRESCIMENTO',
};
